whoisData:
  apikey: at_dE3c8tVnBieCdGwtzUiOFFGfuCQoz
  
  
IOC:
  types:
    - Source IP
    - Destination IP
    - Source Port
    - Destination Port
    - email address
    - domain name
    - URL
    - file hash
    - BTC
    - AS
    - MAC
    - BGP path 
    - SSID

  enrichments:
    SrcIP:
      - asn
      - gip
      - hostname
      - whois

    DestIP:
      - asn
      - gip
      - hostname
      - whois

    SourcePort:
      - na

    DestinationPort:
      - na

    EmailAddress:
      - na

    DomainName:
      - na

    URL:
      - na

    FileHash:
      - na

    BTC:
      - na

    AS:
      - na

    MAC:
      - na

    BGPath:
      - na 

    SSID:
      - na
