apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: neo4j-xyz
  namespace: neo4j
  labels:
    app: neo4j-xyz
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: neo4j-xyz
    spec:
      containers:
      - name: neo4j-xyz
        image: "neo4j"
        imagePullPolicy: "IfNotPresent"
        env:
          - name: NEO4J_AUTH
            value: neo4j/monkeyfarts
          - name: NEO4J_ACCEPT_LICENSE_AGREEMENT
            value: "yes"
        ports:
        - containerPort: 7687
          name: bolt
          protocol: TCP
        securityContext:
          privileged: true
      nodeSelector:
        purpose: worker

---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-xyz-service
  namespace: neo4j
  labels:
    app: neo4j-1
spec:
  type: NodePort
  ports:
  - port: 7687
    targetPort: 7687
    protocol: TCP
    name: bolt
  selector:
    app: neo4j-xyz
